<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rules = [
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 900],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 900],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 900],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 900],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 900],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 900],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],

            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1000],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
            ['usia_balita' => 1, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],

            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
            ['usia_balita' => 1, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             // 2 years old
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1000],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1000],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1000],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1000],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1000],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1000],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 2, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
 
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 2, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1200],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1200],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Ringan', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1400],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Normal', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Pendek', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Sedang', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Rendah', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1600],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Sedang', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Laki-laki', 'kalori' => 1800],
             ['usia_balita' => 3, 'berat_badan' => 'Berat', 'tinggi_badan' => 'Tinggi', 'aktivitas_fisik' => 'Tinggi', 'jenis_kelamin' => 'Perempuan', 'kalori' => 1800], 
        ];

        DB::table('rules')->insert($rules);
    }
}
